
//首页banner
export const GET_HOME_BANNER_FAILURE='GET_HOME_BANNER_FAILURE';
export const GET_HOME_BANNER_SUCCESS='GET_HOME_BANNER_SUCCESS';

//首页公告
export const GET_HOME_NOTICE_FAILURE='GET_HOME_NOTICE_FAILURE';
export const GET_HOME_NOTICE_SUCCESS='GET_HOME_NOTICE_SUCCESS';

//首页理财列表
export const GET_HOME_LIST_START='GET_HOME_LIST_START';
export const GET_HOME_LIST_FAILURE='GET_HOME_LIST_FAILURE';
export const GET_HOME_LIST_SUCCESS='GET_HOME_LIST_SUCCESS';

//理财项目列表
export const GET_FINANCE_LIST_START='GET_FINANCE_LIST_START';
export const GET_FINANCE_LIST_FAILURE='GET_FINANCE_LIST_FAILURE';
export const GET_FINANCE_LIST_SUCCESS='GET_FINANCE_LIST_SUCCESS';

//往期理财项目列表
export const GET_PREVIOUS_FINANCE_LIST_START='GET_PREVIOUS_FINANCE_LIST_START';
export const GET_PREVIOUS_FINANCE_LIST_FAILURE='GET_PREVIOUS_FINANCE_LIST_FAILURE';
export const GET_PREVIOUS_FINANCE_LIST_SUCCESS='GET_PREVIOUS_FINANCE_LIST_SUCCESS';

//账户中心数据
export const GET_ACCOUNT_INFO_START='GET_ACCOUNT_INFO_START';
export const GET_ACCOUNT_INFO_FAILURE='GET_ACCOUNT_INFO_FAILURE';
export const GET_ACCOUNT_INFO_SUCCESS='GET_ACCOUNT_INFO_SUCCESS';
export const GET_ACCOUNT_AVATAR_SOURCE='GET_ACCOUNT_AVATAR_SOURCE';

//登录
export const GET_LOGIN_VALID_PHONE='GET_LOGIN_VALID_PHONE';
export const GET_LOGIN_VALID_PWD='GET_LOGIN_VALID_PWD';
export const IS_SHOW_LOGIN_PASS_WORD='IS_SHOW_LOGIN_PASS_WORD';
export const LOGIN_START='LOGIN_START';
export const LOGIN_FAILURE='LOGIN_FAILURE';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';

//忘记登录密码
export const GET_SET_LOGIN_PWD_VALID_PHONE='GET_SET_LOGIN_PWD_VALID_PHONE';
export const GET_SET_LOGIN_PWD='GET_SET_LOGIN_PWD';
export const IS_SHOW_SET_LOGIN_PASS_WORD='IS_SHOW_SET_LOGIN_PASS_WORD';
export const SET_LOGIN_PWD_SUMMIT_START='SET_LOGIN_PWD_SUMMIT_START';
export const SET_LOGIN_PWD_SUMMIT_FAILURE='SET_LOGIN_PWD_SUMMIT_FAILURE';
export const SET_LOGIN_PWD_SUMMIT_SUCCESS='SET_LOGIN_PWD_SUMMIT_SUCCESS';
export const SET_FORGET_LOGIN_PWD_MESSAGE_TXT='SET_FORGET_LOGIN_PWD_MESSAGE_TXT';

//注册
export const GET_REGISTER_PWD_VALID_PHONE='GET_REGISTER_PWD_VALID_PHONE';
export const GET_REGISTER_PWD='GET_REGISTER_PWD';
export const IS_SHOW_REGISTER_PASS_WORD='IS_SHOW_REGISTER_PASS_WORD';
export const REGISTER_START='REGISTER_START';
export const REGISTER_FAILURE='REGISTER_FAILURE';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_PWD_MESSAGE_TXT='REGISTER_PWD_MESSAGE_TXT';
